layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  sort_by options:
    - stars
    - pushed
  limit: 9
  exclude:
    archived: true
    forks: false
    projects:
    # - repo-name

social_media:
  stackoverflow: 5581565
  twitter: saly3301
  youtube: fJ2lOLzpoM7qj097VvdOWQ
  # behance: your_username
  # dribbble: your_username
  facebook: saly3301
  # hackerrank: your_username
  instagram: saly3301
  # keybase: your_username
  linkedin: caddydz
  # mastodon: your_username
  medium: saly3301
  telegram: caddydz
  # unsplash: your_username
  # vk: your_username
  website: https://salimdj.me

topics:
  - name: Laravel
    web_url: https://github.com/topics/laravel
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/laravel/laravel.png

  - name: Web Backend Development

  - name: Vue.js
    web_url: https://github.com/topics/vuejs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/vue/vue.png
