name: Build and Push Docker Image

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: caddydz/caddydz.github.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}
